# Generated by Django 4.2.7 on 2025-09-25 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('summary', models.TextField()),
                ('full_text', models.TextField()),
                ('act_number', models.CharField(blank=True, max_length=100)),
                ('section', models.CharField(blank=True, max_length=100)),
                ('keywords', models.TextField(blank=True)),
                ('jurisdiction', models.CharField(default='India', max_length=100)),
                ('enacted_date', models.DateField(blank=True, null=True)),
                ('last_amendment', models.DateField(blank=True, null=True)),
                ('references', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laws', to='laws.category')),
            ],
            options={
                'verbose_name': 'Law',
                'verbose_name_plural': 'Laws',
                'ordering': ['-created_at'],
            },
        ),
    ]
